-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBFOA9ypvcU63AU0U
UyKR8ZBjwEi8qYvdhWlNUiGEuMigCgYIKoZIzj0DAQehRANCAASjOxcYDk/2qtrT
fvnakXhM2HjoTOodgbyNCK+laTWhejOowadq41uZoxXTCoXY69IVhOo/ALBPf+4H
8XxTUCKr
-----END PRIVATE KEY-----